### ISSUE TITLE
how to enable sidemenu on super starter?

### ISSUE THREAD

**Issue by whisere** [ionic-team/starters#19]
It seems there is code for menu there already, I am wondering how to enable it, tried to change it in tutorial.ts: this.menu.enable(false); - >this.menu.enable(true); 
but it didn't work. Thanks!

**Comment by brandyscarney** [comment]
Thanks for the issue! Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for questions about the framework. :smile:

A menu can be enabled by the following:

```
this.menu.enable(true);
```

I tested it out in the super starter and it is working. There is an example of this in the starter here: https://github.com/ionic-team/starters/blob/master/ionic-angular/official/super/src/pages/tutorial/tutorial.ts#L71

Here are the API docs for `enable`: http://ionicframework.com/docs/api/components/app/MenuController/#enable

If you are modifying the starter to have multiple menus, you will need to pass in a `side` or `id` in order to enable the correct menu: http://ionicframework.com/docs/api/components/app/MenuController/#multiple-menus-on-the-same-side 

If you are still having issues please reach out on the forum or Slack channel linked above. Thank you!

**Comment by whisere** [comment]
Thank you very much for the information! :) will join the forum and slack.

**Comment by gw00p** [comment]
hi @brandyscarney
i have started a new project with: "ionic start sample super" then "ionic serve" in the project folder.
But the sidemenu don't show after tutorial page (that send the user to the "welcome" page) despite the line of code https://github.com/ionic-team/starters/blob/master/ionic-angular/official/super/src/pages/tutorial/tutorial.ts#L71
Tell's ionic to enable the menu.

Maybe there was some other updates to the starter, after your last reply, that break something?

And in conclusion can you clarify about sidemenu?
There is declaration of the template in app/app.components.ts: 
https://github.com/ionic-team/starters/blob/46297867eedc120defa46cc6f6b75f35a1b77c1a/ionic-angular/official/super/src/app/app.component.ts#L10
and then after there is a property pages with all the pages titles and components (used in the template)

Then there is a menu page (pages/menu) also with template and pages array in the "menu.ts"
https://github.com/ionic-team/starters/tree/master/ionic-angular/official/super/src/pages/menu

Maybe all these questions depends on the fact that i am new to ionic-angular (i developed in ionicjs 1.x), so excuse me.

Thanks in advance for your patience and support!

**Comment by sitepratico** [comment]
on the pages:

ListMasterPage
SearchPage
SettingsPage

include:

    <button ion-button menuToggle>
      <ion-icon name="menu"></ion-icon>
    </button>

inside ion-navbar
