### ISSUE TITLE
[AWS Mobile Hub Starter] - Code Errors when fresh cloning the app and following README

### ISSUE THREAD

**Issue by nawwa** [ionic-team/starters#61]
Hello,

I used the ionic start aws and followed the readme, after the first "ionic serve" i get errors 
First screen : 
![screenshot-2018-3-26 ionic app 1](https://user-images.githubusercontent.com/5871540/37894391-68a87788-30de-11e8-955b-0bfb3eadd9d7.png)
Second : 
![screenshot-2018-3-26 ionic app](https://user-images.githubusercontent.com/5871540/37894393-6a58a6ac-30de-11e8-9256-d7064d72d2fa.png)

Do you have any idea why ?
Maybe a package is not updated ?

**Comment by aitormagan** [comment]
I had the same issue. You can solve it by executing:

```
npm install --save aws-amplify@0.1.36 
```

The issue is that this repo has not a AWS Amplify version and the last version is not compatible with the current Ionic AWS implementation as stated by @beevelop in #52. A possible solution would be to fix the AWS Amplify version in the `ionic.starter.json` file.

BR
Aitor

**Comment by nawwa** [comment]
Thanks for the answer, i solved it the same way !

It strange that @beevelop pushed this without even testing the new version.. Anyway thanks again.

**Comment by beevelop** [comment]
@nawwa Nah, I didn't cause this mess in the first place. I just experienced the very same behaviour as you did 🍻I do definitely agree, that such a bug could and should have been caught by some kind of tests (as builds fail pretty much immediately).

**Comment by nawwa** [comment]
Haha ok @beevelop, no problem
